server:
  port: 8080

logging:
  level:
    root: info

#spring:
#  datasource:
#    type: com.zaxxer.hikari.HikariDataSource
#    url: jdbc:postgresql://localhost:5432/dbswedbankshop
#    username: azovk
#    password:
#  jpa:
#    open-in-view: true
#    show_sql: false
#    hibernate:
#      ddl-auto: validate
#    properties:
#      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
#      hibernate:
#        temp:
#          use_jdbc_metadata_defaults: false


application:
  bankId:
    server:
      url: https://appapi2.test.bankid.com
  swedBank:
    server:
      url: https://api.externalintegration.payex.com
    token: dc2f403f580eaa70514abdf25b634e8e3ece7ddf82691c6044bd9a9e215ae5d6
    paymentOrder:
      default: #other setting values are NOT SUPPORTED by application
        operation: Purchase
        currency: EUR
        language: en-US
        productName: Checkout3
        payer:
          payerReference: not set #doesn`t needed, app uses payer SSN
        orderItems:
          restrictedToInstruments: not set #not implemented
        riskIndicator:
          pickUpAddress: not set #not implemented
      defined: #SUPPORTED settings changes
        description: Test Purchase
        payeeInfo:
          payeeId: 9d813f7a-e019-4918-acc8-2020fb78e60d
          payeeName: Hillel
        riskIndicator:
          giftCardPurchase: false